import type { Metadata } from "next";
import { DM_Sans, Inter  } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/common/Navbar";
import Footer from "@/components/Footer";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const inter = Inter({ 
  variable: "--body-font",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${dmSans.variable} ${inter.variable} antialiased`}
      >
        <Navbar />
        <div className="pt-16">
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}
